name: Test Build (Short) (Linksys Devices)
'on':
  repository_dispatch: null
  workflow_dispatch:

jobs:
  build:
    name: Dispatch to `other-repo`
    runs-on: ubuntu-latest
    # Dispatcher workflow in submodule
    steps:
      - name: Dispatch submodule_push event
        uses: mvasigh/dispatch-action@main
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repo: '@'
          event_type: repository_dispatch
          message: |
            {
              "foo": "bar"
            }
